### ISSUE TITLE
Change the CSS font-family property

### ISSUE THREAD

**Issue by HasanMothaffar** [YamanQD/minesweeper#1]
A wise man once said this: "When in doubt, always choose Comic Sans."

Note:
JK, don't use Comic Sans. Maybe try Poppins?
I've been curious about Github's issue system for a while, so I thought maybe I'd pay a visit to your repository.

**Comment by YamanQD** [comment]
You're right, I'll look into it.
Perhaps you might want to do a pull request, that would be great!
